/**
* Ehab Ebeid
* Script to draw HTML Canvas, generated by Illustrator file,
and much more.
*/

var stage;
var imagenames = ["GES", "OSM", "Platner", "FU", "GE3D"];
var basemaps;

function init() {
  var canvas = document.getElementById("legend");
  var ctx = canvas.getContext("2d");

  draw(ctx);
  stage = new createjs.Stage("canvas");
  stage.enableMouseOver(50);
  basemaps = new createjs.Container;
  drawbm();
  drawstruc();
}

function loadbitmap(image, bname) {
    var bitmap = new createjs.Bitmap(image.src);
    bitmap.x = 0; 
    bitmap.y = 0;
    bitmap.scaleX = .344;
    bitmap.scaleY = .344;
    bitmap.name = bname;
    basemaps.addChild(bitmap);
}

function drawbm() {
    imagevars = [];
    arrayLength = imagenames.length;
    
    for (var i = 0; i < arrayLength; i++) {
        var imagevars;
        imagevars[i] = new Image();
        image = imagevars[i];
        image.src = 'images/' + imagenames[i] + '.jpg';
        image.onload = loadbitmap(image, imagenames[i]);
    }

}

function drawstruc() {
    
    // BEGIN STRUCTURES: 
    
    var structures = new createjs.Container;
    // SENATORIO
    var senc = new createjs.Container;
    var sen = new createjs.Shape();
    sen.graphics.f('rgba(152,78,163,.4)').ss(6,undefined,undefined,10).s('rgba(152,78,163,1)').sd([],0).p('EBOoAiwMACoABjMAAggApMAKHAGCMgAgAAzMAC8ABsMABcgBMMgAQgAJMACDgBzMAAJAALMAICgGEMgUfgMTMgGmAL6').es().ef().cp();
    senc.addChild(sen);
    
    //SMA
    var smac = new createjs.Container;
    var sma = new createjs.Shape();
    sma.graphics.f('rgba(255,127,0,.4)').ss(6,undefined,undefined,10).s('rgba(255,127,0,1)').sd([],0).p('EA0RA5QMAMSgChMgCjgMdMAB8gAcMgBegGmMgB8AAgMgASgBOMgB8AAZMgAVgBVMgB4AAaMgAZgBwMgEoAA+MAAlAC6MgDqAAzMAERAUW').es().ef().cp();
    smac.addChild(sma);
    
    // NUOVO
    var nuoc = new createjs.Container;
    var nuo = new createjs.Shape();
 nuo.graphics.f('rgba(55,125,184,.4)').ss(6,undefined,undefined,10).s('rgba(55,125,184,1)').sd([],0).p('EBMnAm9MgG5APIMgFOgCUMABdgDSMgBrgApMAAmgBMMgBngA3MAAtgBgcAAAAAAgA3gCGACUgBMMABPgCwMgAmgAVMABWgC2MAJNAD4').es().ef().cp();
    nuoc.addChild(nuo);
    
    // CONSERVATORI
    var conc = new createjs.Container;
    var con = new createjs.Shape();
    con.graphics.f('rgba(14,170,28,.4)').ss(6,undefined,undefined,10).s('rgba(14,170,28,1)').sd([],0).p('EBQcA8iMAK4gMmMAerAaoMgCDADcMgECgDVMAAfgAiMgDugDPMgHmADqMgBagCzMgEXACDMgCYgC9MgCUgDjMgBPAA0MgBuABFMgLQgIq').es().ef().cp();
    conc.addChild(con);
    
    
    // JUPITER
    var jupc = new createjs.Container;
    var jup = new createjs.Shape();
    jup.graphics.f('rgba(255,0,61,.4)').ss(6,undefined,undefined,10).s('rgba(255,0,61,1)').sd([],0).p('EBgaBIRMAP0gIwMAIUAOGMgP+AJCMgIKgOY').es().ef().cp();
    jupc.addChild(jup);
    
    // TABULARIUM
    var tabc = new createjs.Container;
    var tab = new createjs.Shape();
    tab.graphics.f('rgba(0,255,255,.4)').ss(6,undefined,undefined,10).s('rgba(0,255,255,1)').sd([],0).p('EBVKAcmMgCZAERMgCngBDMAFEgI+MAUfAMTMgGzAFbMgCigBhMACZgCCMgNmgIc').es().ef().cp();
    tabc.addChild(tab);
    
    // END OF STRUCTURES //
    
    
    // NORTH ARROW
    var leg = new createjs.Container;
    var na = new createjs.Shape(); na.graphics.f('rgba(0,0,0,1)').p('EAENADmcAACAACAABAADgAAAADcgAAAADgABAADgACAACMgAnAAncAAAAAAABxAAAAAAAAAcAAGAAAAAFAAFgAAAAGcgAAAAGgAFAAFgAGgAAMgBxgAAcAAAAAAAAnAAnAAAAAAcAAFAAEgAAAAHgAFAAEcgAFAAFgAHgAAgAFgAFMgBDgBDcAAAAAAABDgBDAAAAAAcAAFgAFAAHAAAAAFAAF').ef().f('rgba(0,0,0,1)').p('EABqAEpcgAAABZABIABIABZAAAcABZAAAABIgBIAAAgBZcAAAgBZgBIgBIgBZgAAcgBZgAAgBIABIgAAABZ').ef().f('rgba(255,255,255,1)').p('EAENADmcAACAACAABAADgAAAADcgAAAADgABAADgACAACMgAnAAncAAAAAAABxAAAAAAAAAcAAGAAAAAFAAFgAAAAGcgAAAAGgAFAAFgAGgAAMgBxgAAcAAAAAAAAnAAnAAAAAAcAAFAAEgAAAAHgAFAAEcgAFAAFgAHgAAgAFgAFMgBDgBDcAAAAAAABDgBDAAAAAAcAAFgAFAAHAAAAAFAAF').ef().cp();
    leg.addChild(na);
 
    var children = [senc,smac,nuoc,conc,jupc,tabc];
    var childnames = ['senatorio','smaracoeli','nuovo','conservatori','jupiter','tabularium'];
    
    // ADD CHILDREN AND ENABLING HOVERING AND CLICKING    
    for (var i = 0; i < children.length; i++) {
        var child = children[i];
        var page = childnames[i];
        child.alpha = 0.7;
        structures.addChild(child);
    }
    
    // EVENT LISTENERS //
    
    // ON HOVER
    senc.addEventListener("mouseover", function() {
        senc.alpha = 1;
        stage.update();
    })

    smac.addEventListener("mouseover", function() {
        smac.alpha = 1;
        stage.update();
    })

    nuoc.addEventListener("mouseover", function() {
        nuoc.alpha = 1;
        stage.update();
    })

    conc.addEventListener("mouseover", function() {
        conc.alpha = 1;
        stage.update();
    })

    jupc.addEventListener("mouseover", function() {
        jupc.alpha = 1;
        stage.update();
    })

    tabc.addEventListener("mouseover", function() {
        tabc.alpha = 1;
        stage.update();
    })

    // ON MOUSEOUT
    senc.addEventListener("mouseout", function() {
        senc.alpha = .7;
        stage.update();
    })

    smac.addEventListener("mouseout", function() {
        smac.alpha = .7;
        stage.update();
    })

    nuoc.addEventListener("mouseout", function() {
        nuoc.alpha = .7;
        stage.update();
    })

    conc.addEventListener("mouseout", function() {
        conc.alpha = .7;
        stage.update();
    })

    jupc.addEventListener("mouseout", function() {
        jupc.alpha = .7;
        stage.update();
    })

    tabc.addEventListener("mouseout", function() {
        tabc.alpha = .7;
        stage.update();
    })
    
    // ON CLICK
    senc.addEventListener("click", function(){
            window.location.href = ('senatorio' + '.html');
        });
    
    smac.addEventListener("click", function(){
            window.location.href = ('smaracoeli' + '.html');
        });
    
    nuoc.addEventListener("click", function(){
            window.location.href = ('nuovo' + '.html');
        });
    
    conc.addEventListener("click", function(){
            window.location.href = ('conservatori' + '.html');
        });
    
    jupc.addEventListener("click", function(){
            window.location.href = ('jupiter' + '.html');
        });
    
    tabc.addEventListener("click", function(){
            window.location.href = ('tabularium' + '.html');
        });
    
    stage.addChild(basemaps);
    structures.cursor = "pointer";
    stage.addChild(structures);
    stage.addChild(leg);
    stage.update();
}


/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function dropdown() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}


/* When the user clicks on a dropdown option,
hide all others */
function bmapf(id) {
    imagenames = ["GES", "OSM", "Platner", "FU", "GE3D"];
    for (var i = 0; i < imagenames.length; i++) {
        map = basemaps.getChildByName(id);
        map.visible = true;
        map = basemaps.getChildByName(imagenames[i]);
        if (id != imagenames[i]) {
            map.visible = false;
            stage.setChildIndex(map,1000)
            stage.update();
        }
    }
   
}

// DRAW LEGEND
function draw(ctx) {

  // layer1/Path
  ctx.save();
  ctx.beginPath();
  ctx.moveTo(58.0, 472.5);
  ctx.lineTo(20.0, 472.5);
  ctx.lineTo(20.0, 434.5);
  ctx.lineTo(58.0, 434.5);
  ctx.lineTo(58.0, 472.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(255, 0, 60, .3)";
  ctx.fill();
  ctx.lineWidth = 6.0;
  ctx.strokeStyle = "rgb(255, 0, 60)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(58.0, 400.5);
  ctx.lineTo(20.0, 400.5);
  ctx.lineTo(20.0, 362.5);
  ctx.lineTo(58.0, 362.5);
  ctx.lineTo(58.0, 400.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(0, 248, 255, .3)";
  ctx.fill();
  ctx.strokeStyle = "rgb(0, 248, 255)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(58.0, 328.5);
  ctx.lineTo(20.0, 328.5);
  ctx.lineTo(20.0, 290.5);
  ctx.lineTo(58.0, 290.5);
  ctx.lineTo(58.0, 328.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(13, 169, 27, .3)";
  ctx.fill();
  ctx.strokeStyle = "rgb(13, 169, 27)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(58.0, 256.5);
  ctx.lineTo(20.0, 256.5);
  ctx.lineTo(20.0, 218.5);
  ctx.lineTo(58.0, 218.5);
  ctx.lineTo(58.0, 256.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(151, 77, 162 , .3)";
  ctx.fill();
  ctx.strokeStyle = "rgb(151, 77, 162)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(58.0, 184.5);
  ctx.lineTo(20.0, 184.5);
  ctx.lineTo(20.0, 146.5);
  ctx.lineTo(58.0, 146.5);
  ctx.lineTo(58.0, 184.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(54, 124, 183, .3)";
  ctx.fill();
  ctx.strokeStyle = "rgb(54, 124, 183)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(58.0, 112.5);
  ctx.lineTo(20.0, 112.5);
  ctx.lineTo(20.0, 74.5);
  ctx.lineTo(58.0, 74.5);
  ctx.lineTo(58.0, 112.5);
  ctx.closePath();
  ctx.fillStyle = "rgba(255, 126, 0, .3)";
  ctx.fill();
  ctx.strokeStyle = "rgb(255, 126, 0)";
  ctx.stroke();

  // layer1/Santa Maria in Aracoeli
  ctx.font = "21.0px Roboto";
  ctx.fillStyle = "rgb(0, 0, 0)";
  ctx.fillText("Santa Maria in Aracoeli", 74.0, 101.2);

  // layer1/Palazzo Nuovo
  ctx.fillText("Palazzo Nuovo", 74.0, 173.2);

  // layer1/Palazzo Senatorio
  ctx.fillText("Palazzo Senatorio", 74.0, 245.2);

  // layer1/Palazzo dei Conservatori
  ctx.fillText("Palazzo dei Conservatori", 74.0, 317.2);

  // layer1/Tabularium
  ctx.fillText("Tabularium", 74.0, 389.2);

  // layer1/Temple of Jupiter
  ctx.fillText("Temple of Jupiter", 74.0, 461.2);

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(342.0, 348.5);
  ctx.lineTo(1.0, 348.5);
  ctx.lineTo(1.0, 640);
  ctx.lineWidth = 3.0;
  ctx.strokeStyle = "rgb(0, 0, 0)";
  ctx.stroke();

  // layer1/Path
  ctx.beginPath();
  ctx.moveTo(1.0, 348.5);
  ctx.lineTo(1.0, 0);
  ctx.stroke();

  // layer1/ANCIENT
  ctx.font = "40.0px Roboto";
  ctx.fillText("ANCIENT", 20.0, 539.5);

  // layer1/EXTANT
  ctx.fillText("EXTANT", 20.0, 44.5);
  ctx.restore();
}

